## reference: http://docs.travis-ci.com/user/languages/r/

language: r
r:
  - bioc-release

cache: packages
bioc_required: true

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"


after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    bash deploy.sh


## notifications:
##   email:
##     on_success: change
##     on_failure: change
